name: Hugo build

on:
  push:
    branches:
      - main
      - master
      - release-*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Enable step debugging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.111.3"
          extended: true

      - name: Build
        run: cd tyk-docs && hugo --minify

      - name: Upload Hugo build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: tyk-docs/public

  htmltest:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Restore source code
        uses: actions/checkout@v3
        with:
          # path: tyk-docs
          ref: ${{ needs.build.head_branch }}

      - name: Download Hugo build artifacts
        uses: actions/download-artifact@v4
        with:
          name: hugo-site
          path: tyk-docs/public/

      - name: Check broken links
        run: |
          ls -l tyk-docs/public/
          cd tyk-docs
          sed -i "s|//tyk.io/docs/nightly/|/|" config.toml
          sed -i -E 's|//tyk\.io/docs/[0-9]+(\.[0-9]+)?/|/|g' config.toml
          sed -i "s|//tyk.io/docs/|/|" config.toml

      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml
