name: CI

on:
  push:
    branches:
      - main
      - master
      - release-*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Enable step debugging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.111.3"
          extended:
            true

            #       - name: Cache Hugo build
            #         uses: actions/cache@v2
            #         with:
            #           path: tyk-docs/public
            #           key: ${{ runner.os }}-hugo-${{ hashFiles('tyk-docs/**') }}

      - name: Build
        run: |
          cd tyk-docs
          sed -i "s|//tyk.io/docs/nightly/|/|" config.toml
          sed -i -E 's|//tyk\.io/docs/[0-9]+(\.[0-9]+)?/|/|g' config.toml
          sed -i "s|//tyk.io/docs/|/|" config.toml
          hugo
          cd ..

      - name: Upload Hugo build artifacts
        uses: actions/upload-artifact@v4
        with:
          name:
            - hugo-site
            - hugo-config
          path:
            - tyk-docs/public
            - tyk-docs/config.toml
          retention-days: 1

  htmltest:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Restore source code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name:
            - hugo-site
            - hugo-config
          path:
            - tyk-docs/public/
            - tyk-docs/config.toml

      - name: Check config.toml has been updated
        run: |
          cat tyk-docs/config.toml

      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config:
            .htmltest.yml

            #   link-checker:
            #     runs-on: ubuntu-22.04
            #     needs: build
            #     steps:
            #       - uses: actions/checkout@v3
            #         with:
            #           submodules: true # Fetch Hugo themes (true OR recursive)
            #           fetch-depth: 0
            #
            #       - name: Check broken links
            #         run: |
            #           base_branch=$(jq -r ".pull_request.base.ref" "$GITHUB_EVENT_PATH")
            #           commit_before_pull_request=$(git merge-base origin/$base_branch HEAD)
            #           echo "Base PR commit: $commit_before_pull_request"
            #
            #           cd tyk-docs && bash ../scripts/urlcheck.sh $commit_before_pull_request
            #
            #       - uses: actions/upload-artifact@v3
            #         if: always()
            #         with:
            #           name: urlcheck-new
            #           path: /tmp/urlcheck.new.json
            #
            #       - uses: actions/upload-artifact@v3
            #         if: always()
            #         with:
            #           name: urlcheck-prev
            #           path: /tmp/urlcheck.prev.json
#       - name: Setup upterm session
#         if: always()
#         uses: lhotari/action-upterm@v1

